config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only:[ :new, :create, :show ] do
    resources :doses, only: [ :index, :new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @ingredients = Ingredient.all
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @cocktail = Cocktail.find(params[:cocktail_id])
    @doses = Dose.where(cocktail_id: params[:cocktail_id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="jumbotron jumbotron-fluid border-bottom border-warning">
  <div class="container">
    <h1 class="display-1 text-warning text-right">VELVET</h1>
    <p class="text-warning text-right"></p>
  </div>
</div>

<ul class="card1-list">
  <h2 class="display-2">COCKTAILS</h2>
  <% @cocktails.each do |cocktail| %>
    <li class="card1">
      <%= link_to cocktail_path(cocktail), class: "card1-image" do %>
        <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key %>
        <% else %>
          <%= image_tag "https://www.unitedstatesofparis.com/wp-content/uploads/2017/12/Secret-8-by-Buddha-Bar-Paris-cocktail-Snowy-Venezia-prosecco-punt-mes-ginger-beer-sirop-maison-saveurs-vin-chaud-hoto-usofparis-blog.jpg" %>
        <% end %>
      <% end %>
      <%= link_to cocktail_path(cocktail), class: "card1-description" do %>
        <h2><%= cocktail.name.upcase %></h2>
        <p><%= cocktail.description %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<div class="container pt-4">
  <h1>Add cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add cocktail", class: "btn btn-warning" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1 class="text-center display-1 text-warning"><%= @cocktail.name.upcase %></h1>
  <div class="row">
    <div class="col-12 justify-content-center d-flex">
      <div class="card my-2" style="width: 28rem;">
        <% if @cocktail.photo.attached? %>
          <%= cl_image_tag @cocktail.photo.key, class: "card-img-top" %>
        <% else %>
          <%= image_tag "https://www.unitedstatesofparis.com/wp-content/uploads/2017/12/Secret-8-by-Buddha-Bar-Paris-cocktail-Snowy-Venezia-prosecco-punt-mes-ginger-beer-sirop-maison-saveurs-vin-chaud-hoto-usofparis-blog.jpg", class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <h4 class="card-title">Composition:</h5>
          <% @cocktail.doses.each do |dose| %>
            <p class="card-text">  <%= dose.description %>
            <%= Ingredient.find(dose.ingredient_id).name %>
            <%= link_to dose_path(dose),
                    method: :delete,
                    data: { confirm: "Are you sure?" }, class: "ml-3 text-warning" do %>
                    <i class="far fa-trash-alt"></i>
                    <% end %>
                  </p>

          <% end %>
        </div>
      </div>

    </div>
     <div class="col justify-content-center d-flex">
        <p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail.id), class: "mx-1 text-warning text-decoration-none btn btn-outline-warning" %></p>
        <p><%= link_to "Back to index", root_path, class: "mx-1 text-warning text-decoration-none btn btn-outline-warning" %></p>
      </div>
  </div>
</div>

app/views/doses/index.html.erb
<div class="container">
  <h1>Doses of <%= @cocktail.name %></h1>
  <% @doses.each do |dose| %>
    <p><%= dose.description %> <%= Ingredient.find(dose.ingredient_id).name %></p>
  <% end %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1 class="text-warning text-center display-1">Add dose to your cocktail</h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "Add dose", class: "btn btn-warning" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-light border-bottom border-warning">
      <%= link_to "VELVET", root_path, class: "navbar-brand text-warning" %>
      <%= link_to "ADD COCKTAIL", new_cocktail_path, class: "btn btn-outline-warning ml-2" %>
    </div>
    <%= yield %>
  </body>
</html>